In [2]:
import pandas as pd
import requests

In [3]:

r = requests.get('https://api.coindesk.com/v1/bpi/currentprice.json')
data = r.json()
df = pd.DataFrame(data=data)
df.head()

,time,disclaimer,chartName,bpi
updated,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
USD,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."

In [4]:
df.describe()

,time,disclaimer,chartName,bpi
count,3,6,6,3
unique,3,1,1,3
top,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
freq,1,6,6,1

In [5]:
df.shape

(6, 4)

In [7]:
df[df['time'] == '2']

Empty DataFrame
Columns: [time, disclaimer, chartName, bpi]
Index: []

In [52]:
df[['disclaimer','bpi']].head()

,disclaimer,bpi
updated,This data was produced from the CoinDesk Bitco...,NaN
updatedISO,This data was produced from the CoinDesk Bitco...,NaN
updateduk,This data was produced from the CoinDesk Bitco...,NaN
USD,This data was produced from the CoinDesk Bitco...,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,This data was produced from the CoinDesk Bitco...,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."

In [8]:
df.iloc[2:9]

,time,disclaimer,chartName,bpi
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
USD,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."
EUR,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'EUR', 'symbol': '&euro;', 'rate': '2..."

In [13]:
df[df['chartName'] == 'Bitcoin']

,time,disclaimer,chartName,bpi
updated,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
USD,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."
EUR,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin,"{'code': 'EUR', 'symbol': '&euro;', 'rate': '2..."

In [14]:
df[['time','bpi']].head()

,time,bpi
updated,"Jun 18, 2023 22:19:00 UTC",NaN
updatedISO,2023-06-18T22:19:00+00:00,NaN
updateduk,"Jun 18, 2023 at 23:19 BST",NaN
USD,NaN,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,NaN,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."

In [16]:
df.iloc[1:3]

,time,disclaimer,chartName,bpi
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...,Bitcoin,NaN
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,Bitcoin,NaN

In [18]:
df['chartName']

updated       Bitcoin
updatedISO    Bitcoin
updateduk     Bitcoin
USD           Bitcoin
GBP           Bitcoin
EUR           Bitcoin
Name: chartName, dtype: object

In [40]:
df[['bpi']]

                                                          bpi
updated                                                   NaN
updatedISO                                                NaN
updateduk                                                 NaN
USD         {'code': 'USD', 'symbol': '&#36;', 'rate': '26...
GBP         {'code': 'GBP', 'symbol': '&pound;', 'rate': '...
EUR         {'code': 'EUR', 'symbol': '&euro;', 'rate': '2...

In [38]:
df.iloc[:, -1]

updated                                                     NaN
updatedISO                                                  NaN
updateduk                                                   NaN
USD           {'code': 'USD', 'symbol': '&#36;', 'rate': '26...
GBP           {'code': 'GBP', 'symbol': '&pound;', 'rate': '...
EUR           {'code': 'EUR', 'symbol': '&euro;', 'rate': '2...
Name: bpi, dtype: object

In [45]:
#select columns in index positions
df_new = df.iloc[:, [0,1,3]]
df_new

,time,disclaimer,bpi
updated,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...,NaN
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...,NaN
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,NaN
USD,NaN,This data was produced from the CoinDesk Bitco...,"{'code': 'USD', 'symbol': '&#36;', 'rate': '26..."
GBP,NaN,This data was produced from the CoinDesk Bitco...,"{'code': 'GBP', 'symbol': '&pound;', 'rate': '..."
EUR,NaN,This data was produced from the CoinDesk Bitco...,"{'code': 'EUR', 'symbol': '&euro;', 'rate': '2..."

In [46]:
#select columns in index range
df_new = df.iloc[:, 0:3]
df_new

,time,disclaimer,chartName
updated,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...,Bitcoin
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...,Bitcoin
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...,Bitcoin
USD,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin
GBP,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin
EUR,NaN,This data was produced from the CoinDesk Bitco...,Bitcoin

In [47]:
#select columns called 
df_new = df [ ['time', 'disclaimer']]
df_new

,time,disclaimer
updated,"Jun 18, 2023 22:19:00 UTC",This data was produced from the CoinDesk Bitco...
updatedISO,2023-06-18T22:19:00+00:00,This data was produced from the CoinDesk Bitco...
updateduk,"Jun 18, 2023 at 23:19 BST",This data was produced from the CoinDesk Bitco...
USD,NaN,This data was produced from the CoinDesk Bitco...
GBP,NaN,This data was produced from the CoinDesk Bitco...
EUR,NaN,This data was produced from the CoinDesk Bitco...

In [49]:
#select and print 4 rows in a pandas data frame
get_rows = df.head (4) 
print (get_rows)

                                 time  \
updated     Jun 18, 2023 22:19:00 UTC
updatedISO  2023-06-18T22:19:00+00:00
updateduk   Jun 18, 2023 at 23:19 BST
USD                               NaN

                                                   disclaimer chartName  \
updated     This data was produced from the CoinDesk Bitco...   Bitcoin
updatedISO  This data was produced from the CoinDesk Bitco...   Bitcoin
updateduk   This data was produced from the CoinDesk Bitco...   Bitcoin
USD         This data was produced from the CoinDesk Bitco...   Bitcoin

                                                          bpi
updated                                                   NaN
updatedISO                                                NaN
updateduk                                                 NaN
USD         {'code': 'USD', 'symbol': '&#36;', 'rate': '26...